blueblog/blueprints/admin.py
'''
Author: han wu 
Date: 2021-12-23 09:36:26
LastEditTime: 2022-01-02 10:27:56
LastEditors: your name
Description: 
FilePath: /BlueBlog_Demo/blueblog/blueprints/admin.py
~~~~~~~~~吼吼吼~~~~~~~~~~
'''
import os

from flask import render_template, flash, redirect, url_for, request, current_app, Blueprint, send_from_directory
from flask_login import login_required, current_user
from flask_ckeditor import upload_success, upload_fail

from blueblog.extensions import db
from blueblog.forms import SettingForm, PostForm, CategoryForm, LinkForm
from blueblog.models import Post, Category, Comment
from blueblog.utils import redirect_back, allowed_file

admin_bp = Blueprint(
	"admin", __name__
)



@admin_bp.route('/post/<int:post_id>/set-comment', methods=['POST'])
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post.can_comment:
        post.can_comment = False
        flash('Comment disabled.', 'success')
    else:
        post.can_comment = True
        flash('Comment enabled.', 'success')
    db.session.commit()
    return redirect_back()

@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.', 'success')
    return redirect_back()

blueblog/blueprints/blog.py
'''
Author: han wu 
Date: 2021-12-23 09:36:13
LastEditTime: 2022-01-02 10:43:59
LastEditors: your name
Description: auth.
FilePath: /BlueBlog_Demo/blueblog/blueprints/blog.py
~~~~~~~~~吼吼吼~~~~~~~~~~
'''

from flask import render_template, Blueprint,request,current_app,url_for,flash,redirect
from blueblog.models import Post,Category,Comment
from flask_login import current_user
from blueblog.forms import AdminCommentForm, CommentForm
from blueblog.extensions import db
from blueblog.emails import send_new_comment_email, send_new_reply_email


blog_bp = Blueprint(
	'blog', __name__
)

@blog_bp.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUEBLOG_POST_PER_PAGE'] # 因为create_app配置成了工厂函数，所以得话就需要使用current_app.config得方式来调用配置好的config文件
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/index.html',  pagination = pagination, posts = posts)

@blog_bp.route('/about')
def about():
    return render_template('blog/about.html')

@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUEBLOG_POST_PER_PAGE']
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/category.html', category = category, pagination = pagination, posts = posts)

@blog_bp.route('/post/<int:post_id>', methods=['GET','POST'])
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUEBLOG_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post).filter_by(reviewed=True).order_by(Comment.timestamp.asc()).paginate(
        page, per_page)
    comments = pagination.items

    if current_user.is_authenticated:
        form = AdminCommentForm()
        form.author.data = current_user.name
        form.email.data = current_app.config['BLUEBLOG_EMAIL']
        form.site.data = url_for('.index')
        from_admin = True
        reviewed = True
    else:
        form = CommentForm()
        from_admin = False
        reviewed = False

    if form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        site = form.site.data
        body = form.body.data
        comment = Comment(
            author=author, email=email, site=site, body=body,
            from_admin=from_admin, post=post, reviewed=reviewed)
        replied_id = request.args.get('reply')
        if replied_id:
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
            send_new_reply_email(replied_comment)
        db.session.add(comment)
        db.session.commit()
        if current_user.is_authenticated:  # send message based on authentication status
            flash('Comment published.', 'success')
        else:
            flash('Thanks, your comment will be published after reviewed.', 'info')
            send_new_comment_email(post)  # send notification email to admin
        return redirect(url_for('.show_post', post_id=post_id))
    return render_template('blog/post.html', post=post, pagination=pagination, form=form, comments=comments)

@blog_bp.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if not comment.post.can_comment:
        flash('Comment is disabled.', 'warning')
        return redirect(url_for('.show_post', post_id=comment.post.id))
    return redirect(
        url_for('.show_post', post_id=comment.post_id, reply=comment_id, author=comment.author) + '#comment-form')

blueblog/templates/blog/_posts.html
<!--
 * @Author: han wu 
 * @Date: 2021-12-25 23:18:22
 * @LastEditTime: 2021-12-27 08:58:24
 * @LastEditors: your name
 * @Description: 
 * @FilePath: \BlueBlog_Demo\blueblog\templates\blog\_posts.html
 * ~~~~~~~~~吼吼吼~~~~~~~~~~
-->
{% if posts %}
    {% for post in posts %}
        <h3 class="text-primary"><a href="{{ url_for('blog.show_post', post_id=post.id) }}">{{ post.title }}</a></h3>
        <p>
            {{ post.body|striptags|truncate }}
            <small><a href="{{ url_for('.show_post', post_id=post.id) }}">Read More</a></small>
        </p>
        <small>
            Comments: <a href="{{ url_for('.show_post', post_id=post.id) }}#comments">{{ post.comments|length }}</a>&nbsp;&nbsp;
            Category: <a
                href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>
            <span class="float-right">{{ moment(post.timestamp).format('LL') }}</span>
        </small>
        {% if not loop.last %}
            <hr>
        {% endif %}
    {% endfor %}
{% else %}
    <div class="tip">
        <h5>No posts yet.</h5>
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('admin.new_post') }}">Write Now</a>
        {% endif %}
    </div>
{% endif %}

blueblog/templates/blog/_sidebar.html
<!--
 * @Author: han wu 
 * @Date: 2021-12-25 20:31:09
 * @LastEditTime: 2021-12-25 23:17:21
 * @LastEditors: your name
 * @Description:  边栏布局模板 
 * @FilePath: /BlueBlog_Demo/blueblog/templates/blog/_sidebar.html
 * ~~~~~~~~~吼吼吼~~~~~~~~~~
-->


{% if categories %}
    <div class="card mb-3">
        <div class="card-header">Categories</div>
        <ul class="list-group list-group-flush">
            {% for category in categories %}
                <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ url_for('blog.show_category', category_id=category.id) }}">
                        {{ category.name }}
                    </a>
                    <span class="badge badge-primary badge-pill"> {{ category.posts|length }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

blueblog/templates/blog/category.html
<!--
 * @Author: han wu 
 * @Date: 2022-01-01 08:12:13
 * @LastEditTime: 2022-01-01 08:12:43
 * @LastEditors: your name
 * @Description: 
 * @FilePath: /BlueBlog_Demo/blueblog/templates/blog/category.html
 * ~~~~~~~~~吼吼吼~~~~~~~~~~
-->

{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Category: {{ category.name }}</h1>
        <p class="text-muted">{{ category.posts|length }} posts</p>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include "blog/_posts.html" %}
            <div class="page-footer">{{ render_pagination(pagination) }}</div>
        </div>
        <div class="col-sm-4 sidebar">
            {% include "blog/_sidebar.html" %}
        </div>
    </div>
{% endblock %}

blueblog/templates/blog/index.html
<!--
 * @Author: han wu 
 * @Date: 2021-12-25 22:31:46
 * @LastEditTime: 2021-12-26 18:38:34
 * @LastEditors: your name
 * @Description: 
 * @FilePath: /BlueBlog_Demo/blueblog/templates/blog/index.html
 * ~~~~~~~~~吼吼吼~~~~~~~~~~
-->
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pager %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="page-header">
        <h1 class="display-3">{{ admin.blog_title|default('Blog Title') }}</h1>
        <h4 class="text-muted">&nbsp;{{ admin.blog_sub_title|default('Blog Subtitle') }}</h4>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include 'blog/_posts.html' %}
            {% if posts %}
                <div class="page-footer">{{ render_pager(pagination) }}</div>
            {% endif %}
        </div>
        <div class="col-sm-4 sidebar">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

blueblog/templates/blog/post.html
<!--
 * @Author: han wu 
 * @Date: 2021-12-26 20:24:14
 * @LastEditTime: 2022-01-02 10:41:31
 * @LastEditors: your name
 * @Description: 
 * @FilePath: /BlueBlog_Demo/blueblog/templates/blog/post.html
 * ~~~~~~~~~吼吼吼~~~~~~~~~~
-->
{% extends "base.html" %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'bootstrap/form.html' import render_form %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
	<div class="page-header">
		<h1>{{ post.title }}</h1>
		<small>
			Category: <a href="{{url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a></small><br>
            Date: {{ moment(post.timestamp).format('LL') }}
		</small>
	</div>
	<div class="row">
        <div class="col-sm-8">
            {{ post.body|safe }}
            <hr>
            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".postLinkModal">Share
            </button>
            <div class="modal fade postLinkModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Permalink</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <input type="text" class="form-control"
                                       value="{{ url_for('.show_post', post_id=post.id, _external=True) }}" readonly>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="comments" id="comments">
                <h3>{{ pagination.total }} Comments
                    <small>
                        <a href="{{ url_for('.show_post', post_id=post.id, page=pagination.pages or 1) }}#comments">
                            latest</a>
                    </small>
                    {% if current_user.is_authenticated %}
                        <form class="float-right" method="post"
                              action="{{ url_for('admin.set_comment', post_id=post.id, next=request.full_path) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                            <button type="submit" class="btn btn-warning btn-sm">
                                {% if post.can_comment %}Disable{% else %}Enable{% endif %} Comment
                            </button>
                        </form>
                    {% endif %}
                </h3>
                {% if comments %}
                    <ul class="list-group">
                        {% for comment in comments %}
                            <li class="list-group-item list-group-item-action flex-column">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">
                                        <a href="{% if comment.site %}{{ comment.site }}{% else %}#{% endif %}"
                                           target="_blank">
                                            {% if comment.from_admin %}
                                                {{ admin.name }}
                                            {% else %}
                                                {{ comment.author }}
                                            {% endif %}
                                        </a>
                                        {% if comment.from_admin %}
                                            <span class="badge badge-primary">Author</span>{% endif %}
                                        {% if comment.replied %}<span class="badge badge-light">Reply</span>{% endif %}
                                    </h5>
                                    <small data-toggle="tooltip" data-placement="top" data-delay="500"
                                           data-timestamp="{{ comment.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
                                        {{ moment(comment.timestamp).fromNow() }}
                                    </small>
                                </div>
                                {% if comment.replied %}
                                    <p class="alert alert-dark reply-body">{{ comment.replied.author }}:
                                        <br>{{ comment.replied.body }}
                                    </p>
                                {%- endif -%}
                                <p class="mb-1">{{ comment.body }}</p>
                                <div class="float-right">
                                    <a class="btn btn-light btn-sm"
                                       href="{{ url_for('.reply_comment', comment_id=comment.id) }}">Reply</a>
                                    {% if current_user.is_authenticated %}
                                        <a class="btn btn-light btn-sm" href="mailto:{{ comment.email }}">Email</a>
                                        <form class="inline" method="post"
                                              action="{{ url_for('admin.delete_comment', comment_id=comment.id, next=request.full_path) }}">
                                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                            <button type="submit" class="btn btn-danger btn-sm"
                                                    onclick="return confirm('Are you sure?');">Delete
                                            </button>
                                        </form>
                                    {% endif %}
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <div class="tip"><h5>No comments.</h5></div>
                {% endif %}
            </div>
            {% if comments %}
                {{ render_pagination(pagination, fragment='#comments') }}
            {% endif %}
            {% if request.args.get('reply') %}
                <div class="alert alert-dark">
                    Reply to <strong>{{ request.args.get('author') }}</strong>:
                    <a class="float-right" href="{{ url_for('.show_post', post_id=post.id) }}">Cancel</a>
                </div>
            {% endif %}
            {% if post.can_comment %}
                <div id="comment-form">
                    {{ render_form(form, action=request.full_path) }}
                </div>
            {% else %}
                <div class="tip"><h5>Comment disabled.</h5></div>
            {% endif %}
        </div>
		<div class="col-sm-4 sidebar">
			{% include "blog/_sidebar.html" %}
		</div>
	</div>
	
{% endblock %}